//! # D-Bus interface proxy for: `com.redhat.lvmdbus1.Lv`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `Interface '/com/redhat/lvmdbus1/ThinPool/0' from service 'com.redhat.lvmdbus1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.redhat.lvmdbus1.Lv",
    default_service = "com.redhat.lvmdbus1",
    default_path = "/com/redhat/lvmdbus1/ThinPool/0"
)]
pub trait Lv {
    /// Activate method
    fn activate(
        &self,
        control_flags: u64,
        tmo: i32,
        activate_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Deactivate method
    fn deactivate(
        &self,
        control_flags: u64,
        tmo: i32,
        activate_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Move method
    fn move_(
        &self,
        pv_src_obj: &zbus::zvariant::ObjectPath<'_>,
        pv_source_range: &(u64, u64),
        pv_dests_and_ranges: &[&(&zbus::zvariant::ObjectPath<'_>, u64, u64)],
        tmo: i32,
        move_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Remove method
    fn remove(
        &self,
        tmo: i32,
        remove_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Rename method
    fn rename(
        &self,
        name: &str,
        tmo: i32,
        rename_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// RepairRaidLv method
    fn repair_raid_lv(
        &self,
        new_pvs: &[&zbus::zvariant::ObjectPath<'_>],
        tmo: i32,
        repair_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Resize method
    fn resize(
        &self,
        new_size_bytes: u64,
        pv_dests_and_ranges: &[&(&zbus::zvariant::ObjectPath<'_>, u64, u64)],
        tmo: i32,
        resize_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Snapshot method
    fn snapshot(
        &self,
        name: &str,
        optional_size: u64,
        tmo: i32,
        snapshot_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// TagsAdd method
    fn tags_add(
        &self,
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// TagsDel method
    fn tags_del(
        &self,
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// WriteCacheLv method
    fn write_cache_lv(
        &self,
        lv_object: &zbus::zvariant::ObjectPath<'_>,
        tmo: i32,
        cache_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;
}
