//! # D-Bus interface proxy for: `com.redhat.lvmdbus1.LvCommon`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `Interface '/com/redhat/lvmdbus1/ThinPool/0' from service 'com.redhat.lvmdbus1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.redhat.lvmdbus1.LvCommon",
    default_service = "com.redhat.lvmdbus1",
    default_path = "/com/redhat/lvmdbus1/ThinPool/0"
)]
pub trait LvCommon {
    /// Active property
    #[zbus(property)]
    fn active(&self) -> zbus::Result<bool>;

    /// AllocationPolicy property
    #[zbus(property)]
    fn allocation_policy(&self) -> zbus::Result<(String, String)>;

    /// Attr property
    #[zbus(property)]
    fn attr(&self) -> zbus::Result<String>;

    /// CopyPercent property
    #[zbus(property)]
    fn copy_percent(&self) -> zbus::Result<u32>;

    /// DataPercent property
    #[zbus(property)]
    fn data_percent(&self) -> zbus::Result<u32>;

    /// Devices property
    #[zbus(property)]
    #[allow(clippy::type_complexity)]
    fn devices(
        &self,
    ) -> zbus::Result<Vec<(zbus::zvariant::OwnedObjectPath, Vec<(u64, u64, String)>)>>;

    /// FixedMinor property
    #[zbus(property)]
    fn fixed_minor(&self) -> zbus::Result<bool>;

    /// Health property
    #[zbus(property)]
    fn health(&self) -> zbus::Result<(String, String)>;

    /// HiddenLvs property
    #[zbus(property)]
    fn hidden_lvs(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// IsThinPool property
    #[zbus(property)]
    fn is_thin_pool(&self) -> zbus::Result<bool>;

    /// IsThinVolume property
    #[zbus(property)]
    fn is_thin_volume(&self) -> zbus::Result<bool>;

    /// MetaDataPercent property
    #[zbus(property)]
    fn meta_data_percent(&self) -> zbus::Result<u32>;

    /// MetaDataSizeBytes property
    #[zbus(property)]
    fn meta_data_size_bytes(&self) -> zbus::Result<u64>;

    /// MovePv property
    #[zbus(property)]
    fn move_pv(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// OriginLv property
    #[zbus(property)]
    fn origin_lv(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Path property
    #[zbus(property)]
    fn path(&self) -> zbus::Result<String>;

    /// Permissions property
    #[zbus(property)]
    fn permissions(&self) -> zbus::Result<(String, String)>;

    /// PoolLv property
    #[zbus(property)]
    fn pool_lv(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Roles property
    #[zbus(property)]
    fn roles(&self) -> zbus::Result<Vec<String>>;

    /// SegType property
    #[zbus(property)]
    fn seg_type(&self) -> zbus::Result<Vec<String>>;

    /// SizeBytes property
    #[zbus(property)]
    fn size_bytes(&self) -> zbus::Result<u64>;

    /// SkipActivation property
    #[zbus(property)]
    fn skip_activation(&self) -> zbus::Result<bool>;

    /// SnapPercent property
    #[zbus(property)]
    fn snap_percent(&self) -> zbus::Result<u32>;

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<(String, String)>;

    /// SyncPercent property
    #[zbus(property)]
    fn sync_percent(&self) -> zbus::Result<u32>;

    /// Tags property
    #[zbus(property)]
    fn tags(&self) -> zbus::Result<Vec<String>>;

    /// TargetType property
    #[zbus(property)]
    fn target_type(&self) -> zbus::Result<(String, String)>;

    /// Uuid property
    #[zbus(property)]
    fn uuid(&self) -> zbus::Result<String>;

    /// Vg property
    #[zbus(property)]
    fn vg(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// VolumeType property
    #[zbus(property)]
    fn volume_type(&self) -> zbus::Result<(String, String)>;

    /// ZeroBlocks property
    #[zbus(property)]
    fn zero_blocks(&self) -> zbus::Result<bool>;
}
