//! # D-Bus interface proxy for: `com.redhat.lvmdbus1.Manager`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `Interface '/com/redhat/lvmdbus1/Manager' from service 'com.redhat.lvmdbus1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.redhat.lvmdbus1.Manager",
    default_service = "com.redhat.lvmdbus1",
    default_path = "/com/redhat/lvmdbus1/Manager"
)]
pub trait Manager {
    /// ExternalEvent method
    fn external_event(&self, command: &str) -> zbus::Result<i32>;

    /// FlightRecorderDump method
    fn flight_recorder_dump(&self) -> zbus::Result<()>;

    /// LookUpByLvmId method
    fn look_up_by_lvm_id(&self, key: &str) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// PvCreate method
    fn pv_create(
        &self,
        device: &str,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// PvScan method
    #[allow(clippy::too_many_arguments)]
    fn pv_scan(
        &self,
        activate: bool,
        cache: bool,
        device_paths: &[&str],
        major_minors: &[&(i32, i32)],
        tmo: i32,
        scan_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Refresh method
    fn refresh(&self) -> zbus::Result<u64>;

    /// UseLvmShell method
    fn use_lvm_shell(&self, yes_no: bool) -> zbus::Result<bool>;

    /// VgCreate method
    fn vg_create(
        &self,
        name: &str,
        pv_object_paths: &[&zbus::zvariant::ObjectPath<'_>],
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// Version property
    #[zbus(property)]
    fn version(&self) -> zbus::Result<String>;
}
