//! # D-Bus interface proxy for: `com.redhat.lvmdbus1.ThinPool`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `Interface '/com/redhat/lvmdbus1/ThinPool/0' from service 'com.redhat.lvmdbus1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.redhat.lvmdbus1.ThinPool",
    default_service = "com.redhat.lvmdbus1",
    default_path = "/com/redhat/lvmdbus1/ThinPool/0"
)]
pub trait ThinPool {
    /// LvCreate method
    fn lv_create(
        &self,
        name: &str,
        size_bytes: u64,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// DataLv property
    #[zbus(property)]
    fn data_lv(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// MetaDataLv property
    #[zbus(property)]
    fn meta_data_lv(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;
}
