//! # D-Bus interface proxy for: `com.redhat.lvmdbus1.Vg`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `Interface '/com/redhat/lvmdbus1/Vg/0' from service 'com.redhat.lvmdbus1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.redhat.lvmdbus1.Vg",
    default_service = "com.redhat.lvmdbus1",
    default_path = "/com/redhat/lvmdbus1/Vg/0"
)]
pub trait Vg {
    /// Activate method
    fn activate(
        &self,
        control_flags: u64,
        tmo: i32,
        activate_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// AllocationPolicySet method
    fn allocation_policy_set(
        &self,
        policy: &str,
        tmo: i32,
        policy_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Change method
    fn change(
        &self,
        tmo: i32,
        change_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// CreateCachePool method
    fn create_cache_pool(
        &self,
        meta_data_lv: &zbus::zvariant::ObjectPath<'_>,
        data_lv: &zbus::zvariant::ObjectPath<'_>,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// CreateThinPool method
    fn create_thin_pool(
        &self,
        meta_data_lv: &zbus::zvariant::ObjectPath<'_>,
        data_lv: &zbus::zvariant::ObjectPath<'_>,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// Deactivate method
    fn deactivate(
        &self,
        control_flags: u64,
        tmo: i32,
        activate_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Extend method
    fn extend(
        &self,
        pv_object_paths: &[&zbus::zvariant::ObjectPath<'_>],
        tmo: i32,
        extend_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// LvCreate method
    fn lv_create(
        &self,
        name: &str,
        size_bytes: u64,
        pv_dests_and_ranges: &[&(&zbus::zvariant::ObjectPath<'_>, u64, u64)],
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// LvCreateLinear method
    fn lv_create_linear(
        &self,
        name: &str,
        size_bytes: u64,
        thin_pool: bool,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// LvCreateMirror method
    fn lv_create_mirror(
        &self,
        name: &str,
        size_bytes: u64,
        num_copies: u32,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// LvCreateRaid method
    #[allow(clippy::too_many_arguments)]
    fn lv_create_raid(
        &self,
        name: &str,
        raid_type: &str,
        size_bytes: u64,
        num_stripes: u32,
        stripe_size_kb: u32,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// LvCreateStriped method
    #[allow(clippy::too_many_arguments)]
    fn lv_create_striped(
        &self,
        name: &str,
        size_bytes: u64,
        num_stripes: u32,
        stripe_size_kb: u32,
        thin_pool: bool,
        tmo: i32,
        create_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<(
        zbus::zvariant::OwnedObjectPath,
        zbus::zvariant::OwnedObjectPath,
    )>;

    /// MaxLvSet method
    fn max_lv_set(
        &self,
        number: u64,
        tmo: i32,
        max_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// MaxPvSet method
    fn max_pv_set(
        &self,
        number: u64,
        tmo: i32,
        max_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Move method
    fn move_(
        &self,
        pv_src_obj: &zbus::zvariant::ObjectPath<'_>,
        pv_source_range: &(u64, u64),
        pv_dests_and_ranges: &[&(&zbus::zvariant::ObjectPath<'_>, u64, u64)],
        tmo: i32,
        move_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// PvTagsAdd method
    fn pv_tags_add(
        &self,
        pvs: &[&zbus::zvariant::ObjectPath<'_>],
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// PvTagsDel method
    fn pv_tags_del(
        &self,
        pvs: &[&zbus::zvariant::ObjectPath<'_>],
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Reduce method
    fn reduce(
        &self,
        missing: bool,
        pv_object_paths: &[&zbus::zvariant::ObjectPath<'_>],
        tmo: i32,
        reduce_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Remove method
    fn remove(
        &self,
        tmo: i32,
        remove_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// Rename method
    fn rename(
        &self,
        name: &str,
        tmo: i32,
        rename_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// TagsAdd method
    fn tags_add(
        &self,
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// TagsDel method
    fn tags_del(
        &self,
        tags: &[&str],
        tmo: i32,
        tag_options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// UuidGenerate method
    fn uuid_generate(
        &self,
        tmo: i32,
        options: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// AllocAnywhere property
    #[zbus(property)]
    fn alloc_anywhere(&self) -> zbus::Result<bool>;

    /// AllocCling property
    #[zbus(property)]
    fn alloc_cling(&self) -> zbus::Result<bool>;

    /// AllocContiguous property
    #[zbus(property)]
    fn alloc_contiguous(&self) -> zbus::Result<bool>;

    /// AllocNormal property
    #[zbus(property)]
    fn alloc_normal(&self) -> zbus::Result<bool>;

    /// Clustered property
    #[zbus(property)]
    fn clustered(&self) -> zbus::Result<bool>;

    /// Exportable property
    #[zbus(property)]
    fn exportable(&self) -> zbus::Result<bool>;

    /// ExtentCount property
    #[zbus(property)]
    fn extent_count(&self) -> zbus::Result<u64>;

    /// ExtentSizeBytes property
    #[zbus(property)]
    fn extent_size_bytes(&self) -> zbus::Result<u64>;

    /// Fmt property
    #[zbus(property)]
    fn fmt(&self) -> zbus::Result<String>;

    /// FreeBytes property
    #[zbus(property)]
    fn free_bytes(&self) -> zbus::Result<u64>;

    /// FreeCount property
    #[zbus(property)]
    fn free_count(&self) -> zbus::Result<u64>;

    /// LvCount property
    #[zbus(property)]
    fn lv_count(&self) -> zbus::Result<u64>;

    /// Lvs property
    #[zbus(property)]
    fn lvs(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// MaxLv property
    #[zbus(property)]
    fn max_lv(&self) -> zbus::Result<u64>;

    /// MaxPv property
    #[zbus(property)]
    fn max_pv(&self) -> zbus::Result<u64>;

    /// MdaCount property
    #[zbus(property)]
    fn mda_count(&self) -> zbus::Result<u64>;

    /// MdaFree property
    #[zbus(property)]
    fn mda_free(&self) -> zbus::Result<u64>;

    /// MdaSizeBytes property
    #[zbus(property)]
    fn mda_size_bytes(&self) -> zbus::Result<u64>;

    /// MdaUsedCount property
    #[zbus(property)]
    fn mda_used_count(&self) -> zbus::Result<u64>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// Partial property
    #[zbus(property)]
    fn partial(&self) -> zbus::Result<bool>;

    /// Profile property
    #[zbus(property)]
    fn profile(&self) -> zbus::Result<String>;

    /// PvCount property
    #[zbus(property)]
    fn pv_count(&self) -> zbus::Result<u64>;

    /// Pvs property
    #[zbus(property)]
    fn pvs(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Readable property
    #[zbus(property)]
    fn readable(&self) -> zbus::Result<bool>;

    /// Resizeable property
    #[zbus(property)]
    fn resizeable(&self) -> zbus::Result<bool>;

    /// Seqno property
    #[zbus(property)]
    fn seqno(&self) -> zbus::Result<u64>;

    /// Shared property
    #[zbus(property)]
    fn shared(&self) -> zbus::Result<bool>;

    /// SizeBytes property
    #[zbus(property)]
    fn size_bytes(&self) -> zbus::Result<u64>;

    /// SnapCount property
    #[zbus(property)]
    fn snap_count(&self) -> zbus::Result<u64>;

    /// SysId property
    #[zbus(property)]
    fn sys_id(&self) -> zbus::Result<String>;

    /// Tags property
    #[zbus(property)]
    fn tags(&self) -> zbus::Result<Vec<String>>;

    /// Uuid property
    #[zbus(property)]
    fn uuid(&self) -> zbus::Result<String>;

    /// Writeable property
    #[zbus(property)]
    fn writeable(&self) -> zbus::Result<bool>;
}
